# Funding & Sponsorship
# These are supported funding model platforms

github: [] # GitHub Sponsors username (if available)
patreon: # Patreon username
open_collective: # Open Collective username
ko_fi: # Ko-fi username
tidelift: # Tidelift platform-name/package-name
community_bridge: # Community Bridge project name
liberapay: # Liberapay username
issuehunt: # IssueHunt username
otechie: # Otechie username
lfx_crowdfunding: # LFX Crowdfunding project name
custom: # Custom URL (e.g., https://converso-empire.com/donate)
  - https://github.com/Converso-Empire

# Note: Update these links when funding platforms are set up
# For now, users can show support by:
# - Starring the repository
# - Contributing code
# - Reporting bugs
# - Suggesting features
# - Sharing with others
