name: ❓ Question / Help
description: Ask a question or get help using Converso Downloader
title: "[QUESTION] "
labels: ["question", "help-wanted"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ❓ Question / Help
        
        Need help using Converso Downloader? We're here to help!
        
        **Before asking:**
        - Check the [README](https://github.com/Converso-Empire/converso-downloader)
        - Search existing questions
        - Try troubleshooting common issues
        
        ---

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation / Setup
        - Usage / How-to
        - Download Issues
        - FFmpeg / Video Processing
        - Quality / Format Selection
        - Search Functionality
        - Error Messages
        - Performance / Speed
        - Feature Clarification
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What do you need help with?
      placeholder: |
        I'm trying to...
        
        But I'm not sure how to...
    validations:
      required: true

  - type: textarea
    id: tried
    attributes:
      label: What Have You Tried?
      description: What steps have you already taken to solve this?
      placeholder: |
        1. I tried...
        2. I checked...
        3. I searched...
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version are you using?
      placeholder: "v2.1.3"
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you on?
      options:
        - Windows
        - macOS
        - Linux
        - Running from Source
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other information that might be helpful
      placeholder: |
        - Screenshots
        - Error messages
        - System information
        - Anything else relevant
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      description: Please confirm
      options:
        - label: I have read the README documentation
          required: true
        - label: I have searched for similar questions
          required: true
        - label: This is not a bug report (use Bug Report template instead)
          required: true

  - type: markdown
    attributes:
      value: |
        ---
        
        ## 💬 Getting Help
        
        **Response Time:**
        - Questions are typically answered within 24-48 hours
        - Please be patient and respectful
        
        **Community Support:**
        - Other users may help answer your question
        - Feel free to help others too!
        
        **Created by Converso Empire**
        
        © 2025 Converso Empire. All rights reserved.
